export const trainersData = [
  {
    id: 1,
    name: "Ben",
    title: "Muscle Gain Specialist",
    image: "/muscle.jpg",
    bio: "Ben has 8 years of experience in strength training and muscle development. He specializes in creating personalized workout plans for clients looking to build lean muscle mass.",
    expertise: ["Muscle Gain", "Strength Training", "Bodybuilding"],
    availability: "Mon-Fri: 6AM-8PM, Sat-Sun: 8AM-6PM",
    certifications: ["NASM Certified", "ISSA Strength Coach", "Nutrition Specialist"],
    email: "ranathakur345@gmail.com",
    phone: "+91-8712309645",
  },
  {
    id: 2,
    name: "Harry",
    title: "Zumba & Cardio Coach",
    image: "/zumba.jpeg",
    bio: "Harry brings energy and fun to every class. With 10 years of dance and fitness experience, he creates dynamic cardio workouts that feel more like parties than exercise.",
    expertise: ["Zumba", "Cardio", "Dance Fitness", "Weight Loss"],
    availability: "Tue-Thu: 5PM-9PM, Sat: 10AM-2PM",
    certifications: ["Zumba Instructor", "ACE Fitness Professional", "Dance Fitness Certified"],
    email: "harryauth@gym.com",
    phone: "+91-689098787",
  },
  {
    id: 3,
    name: "Priyanka Chaudhary",
    title: "Weight Loss Coach",
    image: "/weight.jpg",
    bio: "Priyanka specializes in comprehensive weight loss programs combining nutrition coaching with personalized fitness routines. She has helped over 200 clients achieve their weight loss goals.",
    expertise: ["Weight Loss", "Nutrition", "Cardio", "HIIT"],
    availability: "Mon-Fri: 7AM-7PM, Sat: 9AM-5PM",
    certifications: ["ACE Trainer", "Nutrition Specialist", "ISSN Certified"],
    email: "priyanka_chaudhary@gym.com",
    phone: "+91-9123872345",
  },
  {
    id: 4,
    name: "Akruti Sharma",
    title: "Yoga & Flexibility Expert",
    image: "/yoga.jpeg",
    bio: "Emma teaches transformative yoga classes that improve flexibility, mental health, and overall wellbeing. Her calming approach makes yoga accessible to beginners and advanced practitioners alike.",
    expertise: ["Yoga", "Flexibility", "Mindfulness", "Stress Relief"],
    availability: "Mon-Fri: 6AM-12PM, 4PM-8PM, Sat-Sun: 8AM-2PM",
    certifications: ["RYT 200 Yoga Instructor", "Pilates Certified", "Meditation Coach"],
    email: "iamtam.3003@gmail.com",
    phone: "+91-8989765463",
  },
  {
    id: 5,
    name: "Shina",
    title: "CrossFit Coach",
    image: "/crossfit.jpeg",
    bio: "Shina brings CrossFit coaching experience from elite training facilities. She designs functional fitness programs that build strength, power, and endurance.",
    expertise: ["CrossFit", "Functional Training", "Olympic Lifting", "Strength"],
    availability: "Mon-Fri: 5AM-10AM, 4PM-8PM, Sat: 8AM-12PM",
    certifications: ["CrossFit Level 2", "Olympic Lifting Coach", "NASM Trainer"],
    email: "meshina@gym.com",
    phone: "+91-8756473827",
  },
  {
    id: 6,
    name: "Marcus Thompson",
    title: "Bulk & Power Trainer",
    image: "/bulk.webp",
    bio: "Marcus specializes in bulk-up programs for serious athletes. He combines strategic nutrition planning with periodized strength training to maximize muscle gains.",
    expertise: ["Bulk", "Power Training", "Muscle Gain", "Strength", "Nutrition"],
    availability: "Mon-Fri: 5AM-9AM, 4PM-9PM, Sun: 2PM-6PM",
    certifications: ["NASM Certified", "Strength Coach", "Nutrition Specialist", "Bulk Specialist"],
    email: "marcus.thompson@gym.com",
    phone: "+91-7865753230",
  },
  {
    id: 7,
    name: "Robin Sachdeva",
    title: "Swimming & Aqua Fitness",
    image: "/swim.jpeg",
    bio: "Robin specializes in aquatic fitness programs including swimming lessons, water aerobics, and rehabilitation exercises. His programs are perfect for joint-friendly training.",
    expertise: ["Swimming", "Aqua Fitness", "Water Aerobics", "Low Impact", "Rehabilitation"],
    availability: "Mon-Fri: 7AM-8AM, 5PM-7PM, Sat-Sun: 10AM-4PM",
    certifications: ["Swim Coach", "Aquatic Fitness Certified", "CPR/AED", "Rehabilitation Specialist"],
    email: "robinsachdeva.12@gym.com",
    phone: "+91-8794657364",
  },
  {
    id: 8,
    name: "Jessica Brown",
    title: "Nutrition & Wellness Coach",
    image: "/i1.jpg",
    bio: "Jessica combines fitness training with comprehensive nutrition coaching. She helps clients understand the connection between food and fitness goals.",
    expertise: ["Nutrition", "Weight Loss", "Wellness", "Meal Planning", "Lifestyle"],
    availability: "Tue-Thu: 10AM-2PM, 6PM-8PM, Fri: 2PM-6PM",
    certifications: ["Registered Dietitian", "Nutrition Specialist", "Health Coach", "Certified Trainer"],
    email: "jessica.brown@gym.com",
    phone: "+91-7675462435",
  },
  {
    id: 12,
    name: "Deepti Sharma",
    title: "Flexibility & Mobility Coach",
    image: "/flexibility.jpg",
    bio: "Deepti specializes in improving flexibility, mobility, and joint health. Her programs help clients recover from injuries and prevent future problems.",
    expertise: ["Flexibility", "Mobility", "Stretching", "Recovery", "Injury Prevention"],
    availability: "Mon-Fri: 8AM-12PM, 3PM-7PM, Sat: 10AM-3PM",
    certifications: ["Flexibility Coach", "Mobility Specialist", "Injury Prevention Expert", "Yoga Certified"],
    email: "deepti.sharma@gym.com",
    phone: "+91-9876543212",
  },
  {
    id: 13,
    name: "Patralekha",
    title: "Endurance & Marathon Trainer",
    image: "/athlete.jpg",
    bio: "Patralekha specializes in training runners and endurance athletes. She creates periodized training programs for marathons, half-marathons, and long-distance running.",
    expertise: ["Running", "Marathon", "Endurance", "Cardio", "Race Preparation"],
    availability: "Mon-Fri: 5AM-7AM, 5PM-7PM, Sat-Sun: 7AM-9AM",
    certifications: ["RRCA Running Coach", "NASM Trainer", "Endurance Specialist"],
    email: "patralekha.334@gym.com",
    phone: "+91-8796784957",
  },
]
